### ISSUE TITLE
Update links to items in DIMES

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/staticAid#31]
## Describe the bug
Links back to DIMES objects ("View in DIMES") are broken now that DIMES-TNG has new URLs.

**Comment by helrond** [comment]
In order to do this reliably, we'll likely need a service which can resolve AS URIs to DIMES URLs. We don't have a language-agnostic way to get from AS URIs to DIMES URLs (or back).

Wondering if a good short-term solution would be to link to DIMES search results for the object title. It's not a direct link, but you can get to it.

**Comment by helrond** [comment]
Pointed to a targeted search result set in DIMES for now.
